config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  # # Index
  # get 'lists', to: 'lists#index', as: :lists

  # # Create new list
  # get 'lists/new', to: 'lists#new', as: :new_list
  # post 'lists', to: 'lists#create'

  # # Show
  # get 'lists/:id', to: 'lists#show', as: :list

  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    # Bookmark takes comment, movie_id and list_id
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie])
    @bookmark.list_id = @list.id
    @bookmark.movie_id = @movie.id
    # TODO: Collect user input through strong params
    @bookmark.save!
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, @movie)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    # @bookmark = Bookmark.find(params[:bookmark_id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container m-4 ">
  <h1>Your lists</h1>

  <% @lists.each do |list| %>
    <%= link_to list_path(list.id) do %>
    <div class="card-body">
      <h4>
        <%= list.name %>
      </h4>
    </div>
    <% end %>
  <% end %>

  <%= link_to "Create a new list", new_list_path, class:" btn btn-info" %>

</div>

app/views/lists/new.html.erb
<%# Do my simple_form %>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<div class="container rows">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card">
      <p>
        <h4> <%= bookmark.movie.title %></h4>
        <%= bookmark.comment %>
      </p>
    </div>
  <% end %>
</div>
<h4>Add your bookmark</h4>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>

  <%= f.input :movie, collection: Movie.all %>
  <%= f.button :submit %>
<% end %>